// Code generated by "stringer -type itemType -output itemtype_string.go ."; DO NOT EDIT

package main

import "fmt"

const _itemType_name = "itemStartitemErroritemDotitemEOFitemLHSitemRHSitemEqualsitemForitemWhileitemSwtichitemFnitemAmpitemSemiitemLeftMetaitemRightMetaitemLeftParenitemRightParenitemNumberitemPipeitemTextitemBackTickitemHereStringitemFnStartitemFnInsideitemNLitemEnvitemIf"

var _itemType_index = [...]uint8{0, 9, 18, 25, 32, 39, 46, 56, 63, 72, 82, 88, 95, 103, 115, 128, 141, 155, 165, 173, 181, 193, 207, 218, 230, 236, 243, 249}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
